[package]
name = "smbuilder-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
duct = "0.13.6"
smbuilder = { path = "../smbuilder" }
